version: '3.8'

services:
  # Next.js Application
  app:
    build: .
    container_name: hesapduragi-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/hesapduragi
      - NEXTAUTH_SECRET=your-super-secret-key-change-this
      - NEXTAUTH_URL=http://localhost:3000
      - JWT_SECRET=your-jwt-secret-change-this
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - hesapduragi-network

  # MongoDB Database
  mongo:
    image: mongo:7
    container_name: hesapduragi-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=hesapduragi
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=your-mongo-password
    restart: unless-stopped
    networks:
      - hesapduragi-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: hesapduragi-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - hesapduragi-network

volumes:
  mongo_data:

networks:
  hesapduragi-network:
    driver: bridge 