version: '3.8'

services:
  # Next.js Application
  app:
    build: .
    container_name: hesapduragi-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - hesapduragi-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: hesapduragi-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./public:/var/www/public:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - hesapduragi-network

volumes:
  mongo_data:

networks:
  hesapduragi-network:
    driver: bridge 